### PR TITLE
Add melos

### PR DESCRIPTION
**Pull request by Hannnes1**
Melos has been added to manage all packages.

For now, there are no scripts except for the built in ones, which I think is enough for now.

`melos bootstrap` has to be run after cloning the repo. Perhaps we should add a note about that in the docs or the README?

### CODE REVIEW

**Comment by nmfisher** [comment]
@Hannnes1 thanks! can you please revise this so we can merge into `develop`?

**Comment by Hannnes1** [comment]
Sure. The base is now updated

**Comment by Hannnes1** [comment]
Sorry, NOW it's correct

**Comment by nmfisher** [comment]
Do we need the `pubspec.lock` and `.iml` files?

**Comment by Hannnes1** [comment]
No. I forgot about the `pubspec.lock`, and the `.iml` files shouldn't be there either...

**Comment by nmfisher** [comment]
Much appreciated!

**Pull request merged**
